deployment:
  ingress:
    enabled: true
    override_yaml:
      metadata:
        annotations:
          kubernetes.io/ingress.class: istio
      spec:
        rules:
          - host: "kiali.${CLUSTER_DOMAIN}"
            http:
              paths:
                - path: /
                  backend:
                    service:
                      name: kiali
                      port:
                        number: 20001
                  pathType: Prefix
  secret_name: "kiali"

server:
  web_fqdn: "kiali.${CLUSTER_DOMAIN}"
  web_schema: "https"
  web_port: 443

login_token:
  expiration_seconds: 36000

external_services:
  prometheus:
    url: "http://prometheus-server.prometheus.svc.cluster.local"
  grafana:
    enabled: true
    url: "http://grafana.grafana.svc.cluster.local"
    in_cluster_url: "http://grafana.grafana.svc.cluster.local"
  tracing:
    enabled: true
    in_cluster_url: "http://jaeger-v2-collector.opentelemetry.svc.cluster.local:16685"
    url: "http://tracing.${CLUSTER_DOMAIN}"
    use_grpc: true
